export const CHANGE_LOADING = "CHANGE_LOADING";

export const CHANGE_SEX = "CHANGE_SEX";
export const CHANGE_AGE = "CHANGE_AGE";
export const CHANGE_HEIGHT = "CHANGE_HEIGHT";
export const CHANGE_WEIGHT = "CHANGE_WEIGHT";
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const CHANGE_TEXT = "CHANGE_TEXT";
export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_ERROR = "CREATE_MESSAGE_ERROR";
