export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";
export const CHANGE_LOADING = "CHANGE_LOADING";
export const CHANGE_NAME = "CHANGE_NAME";
